### PR TITLE
fix: refine bool layer application

### LINKED ISSUE #615: Merging workspace and member configuration doesn't prioritize member objects
From #611:

@jamesmunns:
> Also, the first thing I tried was to put "changelog": false in the workspace, then ONLY enabling the changelog w/ "pull from github" for our overview project, but I think that didn't work (no changelog generated for the overview project).

### PR DESCRIPTION
**Pull request by manyinsects**
Closes #615. I documented the function with all possible cases, too, but I need to check whether this change in behaviour (which I think is Correct) breaks any current ways we recommend people configure oranda.

### CODE REVIEW

**Review by Gankra — CHANGES_REQUESTED** [review]
The way we do inference (mdbook and funding at least) will break with this change, as inference layers currently rely on `self = None` as a way to disable the functionality completely:

https://github.com/axodotdev/oranda/blob/e64fc3122e7ded68aadb1e60bfd5eae49817beca/src/config/components/mdbooks.rs#L100-L110

https://github.com/axodotdev/oranda/blob/e64fc3122e7ded68aadb1e60bfd5eae49817beca/src/config/components/funding.rs#L91-L100

**Comment by manyinsects** [comment]
> The way we do inference (mdbook and funding at least) will break with this change, as inference layers currently rely on self = None as a way to disable the functionality completely:

Correct me if I'm wrong, but inference/autodetect gets applied _last_ and therefore is not affected by these changes, no? It basically always goes last and therefore even if it sets itself to `None`, it shouldn't get overridden by anything calling `apply_bool_layer` after it.

**Comment by manyinsects** [comment]
Case in point: 
image

**Comment by Gankra** [comment]
mm true, I might be thinking too abstractly (wanting previous layers to always properly work with theoretical future layers)

**Comment by manyinsects** [comment]
fair, I guess it's weighing that against what users expect to be correct behaviour...

**Comment by Gankra** [comment]
With this change does setting `mdbook = false` in the workspace config actually work? I would think that it would get clobbered by the package's own config defaulting to not-false.

**Comment by Gankra** [comment]
We can maybe handle that by making `Some(true)` and `None` have different behaviours. Previously the user had no "inheritance" so there was no reason for "no opinion" and "true" to be different, but now explicitly setting = true to override false in the workspace is a thing.

**Comment by manyinsects** [comment]
> With this change does setting mdbook = false in the workspace config actually work? 

it does:
image

**Comment by manyinsects** [comment]
oh you meant the workspace config, one sec

**Comment by manyinsects** [comment]
also works:
image

**Comment by Gankra** [comment]
The case I'm specifically concerned about:

* workspace sets mdbook = false
* package wants to inherit that, doesn't mention mdbook at all
* oranda reads this as the package setting = true and clobbering the workspace

**Comment by manyinsects** [comment]
this doesn't seem to happen, in my example it would have resulted the other dozen members all saying "Building components: mdbook". it seems like we're using the right behaviour here (auto-detect doesn't even happen because we explicitly auto-disabled it, this gets cascaded down correctly)

**Review by Gankra — APPROVED** [review]

**Comment by Gankra** [comment]
Just for posterity: we hashed out the miscommunication in chat, and indeed the initial impl didn't merge workspace setting "= false" into package properly (package would clobber it). The fix was to make `= true` and `= None` genuinely different, with "true" being an explicit override and "None" being "don't change anything".

**Comment by Gankra** [comment]
Also for posterity, with this change we now need to be cognizant of there being like... 3 "stages" of layering:

1. yolo adding whatever info we can (default layer, axoproject layer)
2. user explicit config that should win any disputes (oranda.json, oranda-workspace.json)
3. delicate/careful analysis (autodetect)
  a. auto-removing/validating info
  b. auto-adding info ONLY IF `lhs != None`
  
As long as we maintain this precise ordering of stages, things will work well. But if we start trying to mix them up, things will break (things getting turned back on after validation removed it, user settings getting overridden by axoproject, etc).

**Pull request merged**
