### PR TITLE
Fix console warning

### LINKED ISSUE #88: console warning
Screen Shot 2023-01-21 at 8 38 15 AM

i am not 100% sure what this means, but we should aim for oranda pages to have a clean console to the extent that is within our control

### PR DESCRIPTION
**Pull request by SaraVieira**
closes https://github.com/axodotdev/oranda/issues/88

### CODE REVIEW

**Review by ashleygwilliams — APPROVED** [review]
would be useful to double check this does indeed get rid of the error, but assuming it does, this looks good

**Comment by SaraVieira** [comment]
We can really only check when merged, no? :/

**Comment by SaraVieira** [comment]
Tests are failing because a change in axo-html is required: https://github.com/axodotdev/axohtml/pull/23

**Comment by ashleygwilliams** [comment]
axohtml is published, so i'm gonna snag this and get it over the hump

**Comment by ashleygwilliams** [comment]
annnnnd axohtml needs a patch, 

```
---- site::it_builds_the_site stdout ----
ERROR: <meta http_equiv="Permissions-Policy"> failed to parse attribute value: Matching variant not found
ERROR: rebuild with nightly to print source location
thread 'site::it_builds_the_site' panicked at 'failed to parse string literal', src/site/head.rs:59:9
```

**Pull request merged**
