### PR TITLE
Add nav for pages

### LINKED ISSUE #43: nav for tool page
when we allow additional pages/assets we need to give a way to navigate to the those pages

### PR DESCRIPTION
**Pull request by SaraVieira**
* Adds nav and header
* Hooks up `no_header` option

closes https://github.com/axodotdev/oranda/issues/43
related https://github.com/axodotdev/oranda/issues/24

### CODE REVIEW

**Comment by sarahghp** [comment]
Based on the element discussion, I think the changes I would recommend for this PR are:
 
* putting nav under title
* rebasing to get new CSS
* adding header CSS to the `theme.css` in fringe
* ++ maybe to address https://github.com/axodotdev/oranda/issues/69, but that's a maybe

(anyways that's the bits I captured)

**Comment by SaraVieira** [comment]
CleanShot 2023-01-17 at 17 27 28@2x


CSS was added here and removed from oranda
https://github.com/axodotdev/turbo-axo/pull/177

**Review by ashleygwilliams — APPROVED** [review]
good for now based on pairing

**Comment by sarahghp** [comment]
This looks good to me, but I think we should bring back the Big Header style. The two `h1`s look unbalanced otherwise.

**Pull request merged**
